library(checkmate)
library(curl)
library(lubridate)
library(mockr)
library(rlang)
library(rutils)
library(testthat)

test_check("rutils")

# # For development use only (comment the code after use (Ctrl + Shift + C)).
#
# cffr::cff_write()
# codemetar::write_codemeta()
# covr::package_coverage()
# devtools::check()
# devtools::document()
# devtools::install()
# devtools:test()
# goodpractice::gp()
# lintr::lint_package()
# pkgdown::build_article("x")
# pkgdown::build_favicons(overwrite = TRUE)
# pkgdown::build_reference()
# pkgdown::build_site()
# rutils::update_pkg_versions()
# spelling::spell_check_package()
# spelling::update_wordlist()
# tcltk::tk_choose.files()
# tcltk::tk_choose.dir()
# urlchecker::url_check()
# usethis::use_coverage()
# usethis::use_dev_version()
# usethis::use_dev_version()
# usethis::use_github_action("check-standard")
# usethis::use_logo(tcltk::tk_choose.files())
# usethis::use_release_issue("#.#.#")
# usethis::use_revdep()
# usethis::use_tidy_description()
# usethis::use_version()
